export const types = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    UI_SET_ERROR: 'UI_SET_ERROR',
    UI_SET_SUCCESS: 'UI_SET_SUCCESS',
    UI_REMOVE: 'UI_REMOVE',
    UI_START_LOADING: 'UI_START_LOADING',
    UI_STOP_LOADING: 'UI_STOP_LOADING'
};
