export const types = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',

    UI_SET_ERROR: 'UI_SET_ERROR',
    UI_SET_SUCCESS: 'UI_SET_SUCCESS',
    UI_REMOVE: 'UI_REMOVE',
    UI_START_LOADING: 'UI_START_LOADING',
    UI_STOP_LOADING: 'UI_STOP_LOADING',

    NOTE_ADD: "NOTE_ADD",
    NOTE_ACTIVE: "NOTE_ACTIVE",
    NOTE_LOAD: "NOTE_LOAD",
    NOTE_UPDATE: "NOTE_UPDATE",
    NOTE_FILE_UPLOAD: "NOTE_FILE_UPLOAD",
    NOTE_DELETE: "NOTE_DELETE",
    NOTE_LOGOUT_CLEAN: "NOTE_LOGOUT_CLEAN",
};
